spring.application.name=employee

# Server Configuration
server.port=8080

# PostgreSQL Datasource Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_task_db
spring.datasource.username=postgres
spring.datasource.password=sql123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect